POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###
GET http://localhost:3000/states/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYyMTA2MzA3fQ.5arg9IlEqPf58DKEQ6XiDZDDhAtT0ht8vnxIJJjNjuQ


###
GET http://localhost:3000/states/1/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYyMTA2MzA3fQ.5arg9IlEqPf58DKEQ6XiDZDDhAtT0ht8vnxIJJjNjuQ

###
POST http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYyMTA2MzA3fQ.5arg9IlEqPf58DKEQ6XiDZDDhAtT0ht8vnxIJJjNjuQ

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}



###
GET http://localhost:3000/districts/322/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYyMTA2MzA3fQ.5arg9IlEqPf58DKEQ6XiDZDDhAtT0ht8vnxIJJjNjuQ

###
DELETE http://localhost:3000/districts/1/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYyMTA2MzA3fQ.5arg9IlEqPf58DKEQ6XiDZDDhAtT0ht8vnxIJJjNjuQ

###
PUT http://localhost:3000/districts/322/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYyMTA2MzA3fQ.5arg9IlEqPf58DKEQ6XiDZDDhAtT0ht8vnxIJJjNjuQ

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}


###
GET http://localhost:3000/states/5/stats/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYyMTA2MzA3fQ.5arg9IlEqPf58DKEQ6XiDZDDhAtT0ht8vnxIJJjNjuQ
